kupiekota/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

kupiekota/kupiekota/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('in/', views.InView.as_view(), name="in"),
    path('out/', views.OutView.as_view(), name='out'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('messages/', include('usermsg.urls', namespace='usermsg')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kupiekota/posts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('', views.ListPostsView.as_view(), name='post_list'),
    path('new/', views.CreatePostView.as_view(), name='new'),
    url(r'by/(?P<username>[-\w]+)/all/', views.UserPostsView.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kupiekota/usermsg/urls.py
from django.urls import path
from . import views

app_name = 'usermsg'

urlpatterns = [
    path('', views.UserBoxListView.as_view(), name='userboxlist'),
    path('<int:pk>/', views.detail_box, name='boxdetail'),
    path('new/<post_user>/', views.create_box, name='new_box'),
]

kupiekota/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static '/css/master.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <title>KupieKota</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
      <a class="navbar-brand" href="{% url 'home' %}">KupieKota</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link"
            href="{% url 'posts:for_user' username=user.username %}">
            {{user.username}} Oferty
          </a>
          <a class="nav-item nav-link" href="{% url 'usermsg:userboxlist' %}">Wiadomości</a>
          <a class="nav-item nav-link" href="{% url 'posts:new' %}">Nowa Oferta</a>
          <a class="nav-item nav-link" href="{% url 'posts:post_list' %}">Wszystkie Oferty</a>
          <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Wyloguj Się</a>

          {% else %}
          <a class="nav-item nav-link" href="{% url 'posts:post_list' %}">Wszystkie Oferty</a>
          <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Zaloguj Się</a>
          <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Zarejestruj Się</a>

          {% endif %}


        </div>
      </div>
    </nav>
    <p></p>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

    </script>
  </body>
</html>

kupiekota/templates/in.html
{% extends "base.html" %}
{% block content %}
  <h1>You are now logged in !</h1>
{% endblock content %}

kupiekota/templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1>Witaj na stronie KupieKota</h1>
  <p></p>
  <h6>
    Strona jest portalem z ogłoszeniami która pozwala
    użytkownikom wysyłać wiadomości między sobą.
  </h6>
{% endblock content %}

kupiekota/templates/out.html
{% extends "base.html" %}
{% block content %}
  <h1>Thanks for visiting !</h1>
{% endblock content %}