kupiekota/kupiekota/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('in/', views.InView.as_view(), name="in"),
    path('out/', views.OutView.as_view(), name='out'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('messages/', include('usermsg.urls', namespace='usermsg')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kupiekota/posts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('', views.ListPostsView.as_view(), name='post_list'),
    path('new/', views.CreatePostView.as_view(), name='new'),
    url(r'by/(?P<username>[-\w]+)/all/', views.UserPostsView.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kupiekota/usermsg/urls.py
from django.urls import path
from . import views

app_name = 'usermsg'

urlpatterns = [
    path('', views.UserBoxListView.as_view(), name='userboxlist'),
    path('<int:pk>/', views.detail_box, name='boxdetail'),
    path('new/<post_user>/', views.create_box, name='new_box'),
]

kupiekota/posts/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.FloatField()
    post_image = models.ImageField(upload_to='post_picture', blank=True)
    location = models.CharField(max_length=512)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
            return reverse('posts:single', kwargs={'username': self.user.username,
                                                   'pk': self.pk})

kupiekota/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from . import models
from django.urls import reverse_lazy
from django.http import Http404
from braces.views import SelectRelatedMixin
from django.contrib import messages


from django.contrib.auth import get_user_model
# Create your views here.

User = get_user_model()


class CreatePostView(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ['title', 'post_image', 'description', 'price', 'location']
    model = models.Post
    select_related = ['user']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ListPostsView(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ['user']


class UserPostsView(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetailView(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ['user']
    template_name = 'posts/post_detail.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Post
    success_url = reverse_lazy('posts:post_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Oferta Usunięta")
        return super().delete(*args, **kwargs)

kupiekota/posts/templates/posts/_post.html
<table id="oferta">
    <thead>
      <th>
        <h2 class="card-title" id="tytolpost">{{post.title}}</h2>
      </th>
    </thead>
    <tr>
      <td>
        {% if post.post_image %}
        <img src="{{post.post_image.url}}" width="260px" class="img-thumbnail" alt="Nie działa :(">
        {% else %}
        <p>*Brak obrazu dla tej oferty*</p>
        {% endif %}
      </td>
      <td>
        <h4 class="cena">{{post.price}} PLN</h4>
      </td>
    </tr>
</table>
<p>by:
  <a class="ownerm" href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
    {{post.user.username}}
  </a>
</p>

kupiekota/posts/templates/posts/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Czy chcesz usunąć tą ofertę?</h2>
<p></p>
{% include "posts/_post.html" with post=object %}

<form method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Usuń">
  <a href="{% url 'posts:single' username=user.username pk=object.pk %}">
    Anuluj
  </a>
</form>
{% endblock content %}

kupiekota/posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% block content %}

  <h1>{{post.title}}</h1>
  {% if post.post_image %}
  <img src="{{post.post_image.url}}" width="260px" alt="Nie działa :(">
  {% else %}
  <p>*Brak obrazu dla tej oferty*</p>
  {% endif %}
  <h4>{{post.price}} PLN</h4>

  <p>{{post.description}}</p>

  <p id="smaller-text">Lokalizacja : {{post.location}}</p>
  <p id="smaller-text">Oferta urzytkownika:
    <a href="{% url 'posts:for_user' username=post.user.username %}">
      {{post.user.username}}
    </a>
  </p>
  {% if user == post.user %}
    <a class="btn btn-danger" href="{% url 'posts:delete' pk=post.pk %}">Usuń post</a>
  {% else %}
    <a class="btn msgbutton" href="{% url 'usermsg:new_box' post_user=post.user.username %}">Wiadomość</a>
  {% endif %}
{% endblock content %}

kupiekota/posts/templates/posts/post_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
  <h3>Nowe ogłoszenie:</h3>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form%}
    <input type="submit" value="Dodaj ogłoszenie">
  </form>

{% endblock content %}

kupiekota/posts/templates/posts/post_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Oferty:</h1>
  {% for post in post_list %}
  <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
    <div class="card text-black bg-light">
      <div class="card-body">

    {% include "posts/_post.html" %}
      </div>
    </div>
  </a>
  <p></p>
  {% endfor %}
{% endblock content %}

kupiekota/posts/templates/posts/user_post_list.html
{% extends "base.html" %}
{% block content %}

    <h2 id="owner">Oferty urzytkownika {{post_user.username}} :</h2>

  {% for post in post_list %}
    {% include "posts/_post.html" %}
    <p></p>
  {% endfor %}


{% endblock content %}